services:
  php:
    build:
      dockerfile: ./php/Dockerfile
    container_name: php
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - SYMFONY_ENV=dev
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8085:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mariadb:latest
    container_name: mySQL
    environment:
      MYSQL_DATABASE: book
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3305:3306"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8088:80"
    depends_on:
      - db
    platform: linux/amd64

volumes:
  mysql_data:
